site_name: Jtachan website
site_description: "Findings, thoughts, tutorials, work. Pieces of my mind!"
site_url: "https://jtachan.github.io/"
repo_url: "https://github.com/Jtachan/website/"
repo_name: "Jtachan/website"

nav:
  - Home:
      - Home: index.md
      - About: jgo/about.md
  - Projects:
      - Index: proj_index.md
      - Next up: projects/nextup.md
      - Python:
          - PyBackport: projects/pybackport.md
      - JavaScript:
          - DnD Spell Table: projects/spells.md

exclude_docs: |
  *.txt

theme:
  name: material
  features:
    - announce.dismiss
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.follow

  palette:
    - scheme: rust
      primary: custom
      accent: custom

  font:
    text: Source Serif 4
    code: Source Code Pro

extra_javascript:
  - js/project_table.js
  - https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@400;600;700&family=Source+Code+Pro&display=swap

extra_css:
  - stylesheet/tables.css
  - stylesheet/theme.css

markdown_extensions:
  - admonition  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admonition#supported-types
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - macros:
      module_name: main

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/jtachan
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/jaime-gonzalezg/
