name: Fetch latest DB commits

on:
  schedule:
    - cron: "0 5 * * *"  # 05:00 UTC every day

permissions:
  contents: write

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v5

      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: "Run script"
        run: |
          pip install -r ./scripts/requirements.txt
          python ./scripts/update_db.py

      - name: "Check for git.diff"
        id: changes
        run: |
          git add .\docs\projects_db.json
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: "Commit and push only when needed"
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto-update db.json"
          git push
